# Generated by Django 5.1.1 on 2024-10-21 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoProject.chef'),
        ),
    ]
