# Generated by Django 5.1.1 on 2024-10-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0002_remove_menu_price_category_price_alter_menu_chef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='price',
        ),
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.IntegerField(default=0.0),
        ),
    ]
